---
title: "Acquired and transmitted resistance"
number-sections: true
format:
  html:
    toc: true
    toc-depth: 4
editor: source
editor_options: 
  chunk_output_type: console
#bibliography: references.bib
#csl: the-american-naturalist.csl
---

```{r include = FALSE, eval = FALSE}
# The code that adds the .nojekyll file to the GitHub repository:
file <- ".nojekyll"
file.create(file)
gert::git_add(file)
gert::git_commit("Adding the .nojekyll file")
gert::git_push()
rm(file)
```

```{r include = FALSE, eval = FALSE}
run_all <- function() {
  knitr::purl("index.qmd", "tmp.R", documentation = FALSE)
  source("tmp.R")
  file.remove("tmp.R")  
}

rerun_all <- function() {
  rm(list  = grep("run_all", ls(envir = .GlobalEnv), value = TRUE, invert = TRUE),
     envir = .GlobalEnv)
  run_all()
}
```

```{r include = FALSE}
setHook("plot.new", NULL, action = "replace")

par2 <- function(...) par(..., mgp = c(1.5, .5, 0), bty = "n")

knitr::knit_hooks$set(
  margin = function(before, options, envir) {
    if (before) par2(plt = c(.105, .97, .15, .95)) else NULL
  })

figw <- 7  # default is 7
figh <- 5  # default is 5
eps <- .7

knitr::opts_chunk$set(margin     = TRUE,
                      fig.retina = 2,
                      fig.align  = "center",
                      fig.width  = eps * figw,
                      fig.height = eps * figh) 
```

```{r message = FALSE}
library(deSolve)
library(tibble)
library(dplyr)
library(tidyr)
```

$$
\frac{dS}{dt} = (I_t + I_a + I_s)\gamma + (1 - p)\alpha I_s -
                [(I_t + I_a)c + I_s]\beta S
$$

$$
\frac{dI_s}{dt} = \beta I_s S - (\gamma + \alpha)I_s
$$

$$
\frac{dI_a}{dt} = p\alpha I_s - \gamma I_a
$$

$$
\frac{I_t}{dt} = (I_t + I_a)Sc\beta - \gamma I_t
$$

```{r}
model <- function(time, state, pars) {
  with(as.list(c(state, pars)), {
    incidenceT <- (1 - c) * beta * (Ia + It) * S
    incidenceS <- beta * Is * S
    recoveryS <- gamma * Is
    recoveryA <- gamma * Ia
    recoveryT <- gamma * It
    treated <- alpha * Is
    incidenceA <- p * treated
    
    dS  <- recoveryS + recoveryA + recoveryT + (1 - p) * treated -
           incidenceT - incidenceS
    dIs <- incidenceS - recoveryS - treated
    dIa <- incidenceA - recoveryA
    dIt <- incidenceT - recoveryT
    cIncS <- incidenceS
    cIncA <- incidenceA
    cIncT <- incidenceT
    
    list(c(dS, dIs, dIa, dIt, cIncS, cIncA, cIncT))
  })
}
```


Prevalance is:

$$
\mbox{P} = 1 - \frac{\gamma}{\beta}
$$

Incidence is:

$$
\mbox{I} = (\beta - \gamma)\frac{\gamma}{\beta}
$$

$\beta$ as a function of prevalence and incidence:

$$
\beta = \frac{\mbox{I}}{(1 - \mbox{P})\mbox{P}}
$$

$\gamma$ as a function of prevalence and $\beta$:

$$
\gamma = (1 - \mbox{P})\beta
$$

```{r}
simulate <- function(P, I, alpha, p, c, times = seq(0, 40, le = 512)) {
  S0 <- 1 - P
  beta <- I / (S0 * P)
  gamma <- beta * S0
  print(gamma)
  ode(c(S = S0, Is = P, Ia = 0, It = 0, cIncS = 0, cIncA = 0, cIncT = 0),
      times, model,
      c(beta = beta, gamma = gamma, alpha = alpha, p = p, c = c)) |> 
    as.data.frame() |> 
    as_tibble() |> 
    select(time, starts_with("c")) |> 
    mutate(across(-1, ~ c(diff(.x) / diff(time), NA))) |> 
    setNames(c("time", "incS", "incA", "incT")) |> 
    head(-1)
}
```

```{r}
plots <- function(...) plot(..., type = "s", lwd = 2, axes = FALSE, ann = FALSE)
```

```{r}
plot_output <- function(x) {
  x <- x |> 
    mutate(incR  = incA + incT,
           inc   = incS + incR,
           pincR = incR / inc,
           pincA = incA / incR,
           across(inc, ~ .x * 1e5))
  with(x, {
    plots(time, inc); par(new = TRUE)
    plots(time, pincR, col = "red"); par(new = TRUE)
    plots(time, pincA, col = "orange")
  })
}
```

```{r fig-simulation}
simulate(P = 300 * 1e-5, I = 200 * 1e-5, alpha = .05, p = .5, c = .2) |> 
  plot_output()
```
